### ISSUE TITLE
Sample code on github doesn't work with v1.1.0

### ISSUE THREAD

**Issue by smasonuk** [mariusmuntean/ChartJs.Blazor#124]
When using the v1.1.0 on nuget, and using the example code on the main page, I get a compilation error that it cant find the class 'Chart'. This class isn't in the assembly. I believe the v.1.1.0 on nuget is probably an older version and the documentation relates to the newer version?
![image](https://user-images.githubusercontent.com/118555/83790587-55034300-a690-11ea-83c3-d381f64e0f85.png)

### Which Blazor project type is your bug related to?
client

### Which charts does this bug apply to?
Only tried PieChart.

### To Reproduce
- Get v1.1.0 on nuget
- using the latest version of visual studio 16.6.1
- Use example code and steps on main github page
- Try to compile
- Get error that Chart class doesn't exist.

To get it working I have to use ChartJsPieChart instead.

### Expected behavior
No compilation errors

**Comment by SeppPenner** [comment]
I would say in the nuget version, this is still named `ChartJsPieChart`. (I have looked into the binary file only quickly).

![grafik](https://user-images.githubusercontent.com/9639361/83791324-e9be6e80-a699-11ea-9c59-5701f2776364.png)

@Joelius300 can give you more information for sure :)

**Comment by Joelius300** [comment]
You're both absolutely correct. Thanks for the detailed issue. It's a better version of #113 :)
